### ISSUE TITLE
develop pipeline

### ISSUE THREAD

**Issue by sangttruong** [quangntran/stereonet#5]
For example: https://towardsdatascience.com/architecting-a-machine-learning-pipeline-a847f094d1c7
Project template: https://drivendata.github.io/cookiecutter-data-science/

**Comment by quangntran** [comment]
GraphGym

For both
- Install dependencies (in [Installation](https://github.com/snap-stanford/GraphGym#installation))
- Read [Run a single GNN experiment](https://github.com/snap-stanford/GraphGym#1-run-a-single-gnn-experiment) to get the general idea
- [ ] Figure out the difference between graphgym/config.py and graphgym/contrib/config
- [ ] Figure out what `meters` is (line 43 `meters = create_logger()` in run/main_py.py)

For divvying up 
- [ ] Adjust graphgym/config.py 
- [ ] Adjust run/configs/example.yaml (just need to specify arguments)
- [ ] Adjust main.py
- [ ] Do everything above but for [running a batch](https://github.com/snap-stanford/GraphGym#2-run-a-batch-of-gnn-experiments)
